package javaprojet;

import DatabaseConnection.DBConnect;
import Model.ClientModel;
import Model.Mail;
import com.itextpdf.text.DocumentException;
import jakarta.mail.MessagingException;
import jakarta.mail.internet.ParseException;
import java.io.UnsupportedEncodingException;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.util.Calendar;

public class HomePage extends javax.swing.JFrame {

    private boolean isInitializing = true; //variable pour contrôler l'initialisation
    private String selectedNumCompteE; // Variable pour stocker le numéro de compte sélectionné dans virement
    private String selectedNumCompteB; // Variable pour stocker le numéro de compte sélectionné dans virement
    private String selectedNumCompte;// Variable pour stocker le numéro de compte sélectionné dans prêt
    //  private String selectedNumPret;// Variable pour stocker le numéro de compte sélectionné dans prêt
    private DefaultTableModel clientTableModel;

    public HomePage() {
        initComponents();
        DBConnect dbConnect = new DBConnect();
        dbConnect.dbConnection();
        ClientModel clientModel = new ClientModel(dbConnect);
        initializeComboBox(); // Initialiser le combo box et ajouter l'écouteur
        clientModel.loadNumCompteEnvoyeur(); //Charge les numCompte lors du chargement de la fenêtre
        clientModel.table(); // Charger les données dans la table client
        clientModel.virementTable(); // Charger les données dans la table virement
        clientModel.tablePret(); // Charger les données dans la table preter 
        clientModel.tableRendre("Toute situation"); // Charger les données par défaut 
        initializeSearchField(); // Initialiser le champ de recherche et ajouter l'écouteur
        searchClient(""); // Charger les données initiales
        clientTableModel = (DefaultTableModel) jTableCli.getModel();
        ClientModel.loadClientData(clientTableModel, dbConnect); // Charger les données dans la table client
        jTextFieldNumCompte.setEditable(false);
        isInitializing = false; // L'initialisation est terminée
        jTextFieldnumPret.setEditable(false);
        jTextFieldNumRendu.setEditable(false);
        jTextFieldRestePayer.setEditable(false);
        jTextFieldDateRendu.setEditable(false);
        jTextFieldsituation.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNumCompte = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldNom = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldPrenoms = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldTel = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldMail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldMontant = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCli = new javax.swing.JTable();
        jTextFieldRecherche = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldMontantVirement = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jComboBoxNumCompteEnvoyeur = new javax.swing.JComboBox<>();
        jComboBoxNumCompteBeneficiaire = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableVirement = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxNumComptePret = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldMontantPret = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldnumPret = new javax.swing.JTextField();
        jButtonAnnulerpret = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablePret = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldNumRendu = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldSituation = new javax.swing.JTextField();
        jTextFieldRestePayer = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldDateRendu = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jTextFieldnumpretrendre = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldmontantremboursé = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldsituation = new javax.swing.JTextField();
        jButton18 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableRendre = new javax.swing.JTable();
        jComboBoxaffichagerembourse = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jToolBar1.setRollover(true);

        jButton2.setBackground(new java.awt.Color(0, 255, 51));
        jButton2.setText("Modifier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 51, 0));
        jButton3.setText("Supprimer");
        jButton3.setAutoscrolls(true);
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setText("NumCompte");

        jLabel7.setText("Nom");

        jLabel8.setText("Prenoms");

        jTextFieldPrenoms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrenomsActionPerformed(evt);
            }
        });

        jLabel9.setText("Telephone");

        jTextFieldTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelActionPerformed(evt);
            }
        });

        jLabel10.setText("Mail");

        jLabel11.setText("Montant");

        jLabel5.setFont(new java.awt.Font("Open Sans Semibold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CLIENTS");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldNumCompte)
                    .addComponent(jTextFieldNom)
                    .addComponent(jTextFieldPrenoms)
                    .addComponent(jTextFieldTel)
                    .addComponent(jTextFieldMail)
                    .addComponent(jTextFieldMontant)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNumCompte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPrenoms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldMontant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableCli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableCli.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableCli.setDoubleBuffered(true);
        jTableCli.setDragEnabled(true);
        jTableCli.setInheritsPopupMenu(true);
        jTableCli.setShowHorizontalLines(true);
        jTableCli.setUpdateSelectionOnSort(false);
        jTableCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableCliMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCli);

        jTextFieldRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRechercheActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setText("Ajouter");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel24.setText("Rechercher");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jToolBar1.add(jPanel4);

        jTabbedPane1.addTab("CLIENT", jToolBar1);

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Open Sans Semibold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VIREMENTS");

        jLabel2.setText("Numéro de compte de l'envoyeur :");

        jLabel3.setText("Numéro de compte du bénéficiaire :");

        jLabel4.setText("Montant :");

        jTextFieldMontantVirement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMontantVirementActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 204, 204));
        jButton5.setText("Ajouter");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jComboBoxNumCompteEnvoyeur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NumCompteE" }));
        jComboBoxNumCompteEnvoyeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNumCompteEnvoyeurActionPerformed(evt);
            }
        });

        jComboBoxNumCompteBeneficiaire.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NumCompteB" }));
        jComboBoxNumCompteBeneficiaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNumCompteBeneficiaireActionPerformed(evt);
            }
        });

        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Modifier");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 51, 0));
        jButton7.setText("Supprimer");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(204, 153, 255));
        jButton8.setText("PDF");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(242, 242, 242));
        jButton13.setText("Annuler");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 255, 51));
        jButton4.setText("Modifier");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxNumCompteEnvoyeur, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxNumCompteBeneficiaire, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldMontantVirement, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jButton8)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxNumCompteEnvoyeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxNumCompteBeneficiaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldMontantVirement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton13))
                .addGap(36, 36, 36)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton6)
                    .addComponent(jButton4))
                .addGap(29, 29, 29)
                .addComponent(jButton8)
                .addGap(48, 48, 48))
        );

        jTableVirement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableVirement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableVirementMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTableVirement);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("VIREMENT", jPanel1);

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel12.setFont(new java.awt.Font("Open Sans Semibold", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 153));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("PRÊT");

        jComboBoxNumComptePret.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NumCompte" }));
        jComboBoxNumComptePret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNumComptePretActionPerformed(evt);
            }
        });

        jLabel14.setText("Numéro de compte");

        jLabel15.setText("Montant prêté");

        jButton10.setBackground(new java.awt.Color(0, 204, 204));
        jButton10.setText("Ajouter");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(255, 51, 0));
        jButton9.setText("Supprimer");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(0, 255, 51));
        jButton11.setText("Modifier");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(204, 153, 255));
        jButton12.setText("Email");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel13.setText("Numéro de prêt");

        jButtonAnnulerpret.setBackground(new java.awt.Color(242, 242, 242));
        jButtonAnnulerpret.setText("Annuler");
        jButtonAnnulerpret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerpretActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jComboBoxNumComptePret, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldnumPret, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)))
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                    .addGap(19, 19, 19)
                                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jTextFieldMontantPret, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(jButton12))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonAnnulerpret, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldnumPret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxNumComptePret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldMontantPret, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jButton11))
                .addGap(36, 36, 36)
                .addComponent(jButton9)
                .addGap(18, 18, 18)
                .addComponent(jButton12)
                .addGap(18, 18, 18)
                .addComponent(jButtonAnnulerpret)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jTablePret.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTablePret.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTablePretMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jTablePret);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane3)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("PRÊT", jPanel2);

        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel16.setFont(new java.awt.Font("Open Sans Semibold", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 153));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("REMBOURSEMENT");

        jLabel17.setText("Numéro de remboursement");

        jLabel18.setText("Numéro de prêt");

        jTextFieldRestePayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRestePayerActionPerformed(evt);
            }
        });

        jLabel20.setText("Reste à payer");

        jLabel21.setText("Date de rendu");

        jTextFieldDateRendu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDateRenduActionPerformed(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(0, 255, 51));
        jButton14.setText("Modifier");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(0, 204, 204));
        jButton15.setText("Ajouter");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(255, 51, 0));
        jButton16.setText("Supprimer");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setBackground(new java.awt.Color(204, 153, 255));
        jButton17.setText("Situation");

        jLabel19.setText("montant remboursé");

        jLabel23.setText("Situation");

        jButton18.setText("Annuler");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextFieldmontantremboursé))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldNumRendu)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldnumpretrendre)
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))
                .addGap(0, 22, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                                    .addComponent(jTextFieldDateRendu)))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTextFieldsituation))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel9Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(116, 116, 116))
                                            .addGroup(jPanel9Layout.createSequentialGroup()
                                                .addGap(41, 41, 41)
                                                .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldRestePayer)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldSituation, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)))))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jTextFieldSituation, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNumRendu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldnumpretrendre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldmontantremboursé, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldRestePayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addGap(4, 4, 4)
                .addComponent(jTextFieldsituation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDateRendu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton15)
                    .addComponent(jButton18))
                .addGap(26, 26, 26)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton16)
                    .addComponent(jButton14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jTableRendre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableRendre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableRendreMouseReleased(evt);
            }
        });
        jScrollPane4.setViewportView(jTableRendre);

        jComboBoxaffichagerembourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxaffichagerembourseActionPerformed(evt);
            }
        });

        jLabel22.setText("Affichage :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxaffichagerembourse, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxaffichagerembourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("REMBOURSEMENT", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Modification d'un Client
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String numCompte = jTextFieldNumCompte.getText();
        String nom = jTextFieldNom.getText();
        String prenoms = jTextFieldPrenoms.getText();
        String tel = jTextFieldTel.getText();
        String mail = jTextFieldMail.getText();
        String solde = jTextFieldMontant.getText();

        // Assurez-vous que tous les champs sont remplis
        if (numCompte.isEmpty() || nom.isEmpty() || prenoms.isEmpty() || tel.isEmpty() || mail.isEmpty() || solde.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs");
        } else {
            // Mettre à jour le client
            DBConnect dbConnect = new DBConnect();
            dbConnect.dbConnection();
            ClientModel clientModel = new ClientModel(dbConnect);
            clientModel.updateClient(numCompte, nom, prenoms, tel, mail, solde);
            HomePage.jTextFieldNumCompte.setText("");
            HomePage.jTextFieldNom.setText("");
            HomePage.jTextFieldPrenoms.setText("");
            HomePage.jTextFieldTel.setText("");
            HomePage.jTextFieldMail.setText("");
            HomePage.jTextFieldMontant.setText("");
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

    }//GEN-LAST:event_jButton1MouseClicked

    //Bouton ajouter un Client
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Ouvrir la nouvelle interface AjoutCli
        DBConnect dbConnect = new DBConnect();
        dbConnect.dbConnection();

        if (dbConnect.connection != null) {
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new AjoutCli(dbConnect).setVisible(true);

                }

            });
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    private void jTableCliMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCliMouseReleased

    }//GEN-LAST:event_jTableCliMouseReleased

    private void jTextFieldTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelActionPerformed

    private void jTextFieldPrenomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrenomsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrenomsActionPerformed

    //Supprimer Client
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String numCompte = jTextFieldNumCompte.getText();

        DBConnect dbConnect = new DBConnect();
        dbConnect.dbConnection();
        ClientModel clientModel = new ClientModel(dbConnect);
        clientModel.deleteClient(numCompte);
        HomePage.jTextFieldNumCompte.setText("");
        HomePage.jTextFieldNom.setText("");
        HomePage.jTextFieldPrenoms.setText("");
        HomePage.jTextFieldTel.setText("");
        HomePage.jTextFieldMail.setText("");
        HomePage.jTextFieldMontant.setText("");

    }//GEN-LAST:event_jButton3ActionPerformed

    //Bouton virement ajout
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String numCompteEnvoyeur = (String) jComboBoxNumCompteEnvoyeur.getSelectedItem();
        String numCompteBeneficiaire = (String) jComboBoxNumCompteBeneficiaire.getSelectedItem();
        double montant;
        DBConnect dbConnect = new DBConnect();
        dbConnect.dbConnection();
        ClientModel clientModel = new ClientModel(dbConnect);

        try {
            montant = Double.parseDouble(jTextFieldMontantVirement.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Veuillez entrer un montant valide.", "Erreur de saisie", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (numCompteEnvoyeur.equals(numCompteBeneficiaire)) {
            JOptionPane.showMessageDialog(this, "Vous ne pouvez pas faire un virement vers votre propre compte. Veuillez changer le Bénéficiaire ou l'envoyeur.", "Erreur de Virement", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (clientModel.updateSolde(dbConnect, numCompteEnvoyeur, numCompteBeneficiaire, montant)) {
            try {
                clientModel.addVirement(dbConnect, numCompteEnvoyeur, numCompteBeneficiaire, montant);
            } catch (DocumentException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(this, "Virement effectué avec succès!");
            refreshClientTable(); // Actualiser les données de la table client
            clientModel.virementTable(); // Actualiser les données de la table des virements
        } else {
            // Le message d'erreur spécifique est déjà géré dans updateSolde.
        }
        HomePage.jTextFieldMontantVirement.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void refreshClientTable() {
        DBConnect dbConnect = new DBConnect();
        dbConnect.dbConnection();
        ClientModel.loadClientData(clientTableModel, dbConnect); // Actualiser les données de la table client
    }

    //Liste déroulante de numCompte de l'envoyeur
    private void jComboBoxNumCompteEnvoyeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNumCompteEnvoyeurActionPerformed

        if (isInitializing) {
            return; // Ne pas exécuter cette méthode si nous sommes en cours d'initialisation
        }
        selectedNumCompteE = (String) jComboBoxNumCompteEnvoyeur.getSelectedItem();
        if (selectedNumCompteE != null) {
            // Effectuez ici les actions nécessaires après la sélection d'un élément.
            System.out.println("Numéro de compte sélectionné: " + selectedNumCompteE);
            //JOptionPane.showMessageDialog(this, "Numéro de compte sélectionné: " + selectedNumCompteE);
        }
    }//GEN-LAST:event_jComboBoxNumCompteEnvoyeurActionPerformed

    //liste déroulante de numCompte du bénéficiaire
    private void jComboBoxNumCompteBeneficiaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNumCompteBeneficiaireActionPerformed

        if (isInitializing) {
            return; // Ne pas exécuter cette méthode si nous sommes en cours d'initialisation
        }
        selectedNumCompteB = (String) jComboBoxNumCompteBeneficiaire.getSelectedItem();
        if (selectedNumCompteB != null) {
            // Effectuez ici les actions nécessaires après la sélection d'un élément.
            System.out.println("Numéro de compte sélectionné: " + selectedNumCompteB);
            // JOptionPane.showMessageDialog(this, "Numéro de compte sélectionné: " + selectedNumCompteB);
        }
    }//GEN-LAST:event_jComboBoxNumCompteBeneficiaireActionPerformed


    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

    }
//GEN-LAST:event_jButton6ActionPerformed
    //Bouton supprimer de virement
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String numCompteEnvoyeur = (String) jComboBoxNumCompteEnvoyeur.getSelectedItem();
        String numCompteBeneficiaire = (String) jComboBoxNumCompteBeneficiaire.getSelectedItem();

        DBConnect dbConnect = new DBConnect();
        dbConnect.dbConnection();

        ClientModel clientModel = new ClientModel(dbConnect);
        clientModel.deleteVirement(dbConnect, numCompteEnvoyeur, numCompteBeneficiaire);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTableVirementMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVirementMouseReleased
        jComboBoxNumCompteEnvoyeur.setEditable(false);
    }//GEN-LAST:event_jTableVirementMouseReleased

    //liste déroulante numCompte dans Prêt
    private void jComboBoxNumComptePretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNumComptePretActionPerformed
        if (isInitializing) {
            return; // Ne pas exécuter cette méthode si nous sommes en cours d'initialisation
        }
        selectedNumCompte = (String) jComboBoxNumComptePret.getSelectedItem();
        if (selectedNumCompte != null) {
            // Effectuez ici les actions nécessaires après la sélection d'un élément.
            System.out.println("Numéro de compte sélectionné: " + selectedNumCompte);
            //JOptionPane.showMessageDialog(this, "Numéro de compte sélectionné: " + selectedNumCompteE);
        }
    }//GEN-LAST:event_jComboBoxNumComptePretActionPerformed

    //Bouton ajout prêt
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        String selectNumCompte = (String) jComboBoxNumComptePret.getSelectedItem();
        double solde = Double.parseDouble(jTextFieldMontantPret.getText()); // Corrected to parse as double

        DBConnect dbConnect = new DBConnect();
        dbConnect.dbConnection();

        ClientModel clientModel = new ClientModel(dbConnect);
        try {
            clientModel.addPret(dbConnect, selectNumCompte, solde);
        } catch (MessagingException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }

        HomePage.jTextFieldMontantPret.setText("");

    }//GEN-LAST:event_jButton10ActionPerformed

    //Bouton supprimer prêt
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        int selectedRow = jTablePret.getSelectedRow(); // Obtenez la ligne sélectionnée
        String numPret = (String) jTablePret.getValueAt(selectedRow, 0); // Récupérez le numPret depuis la première colonne

        DBConnect dbConnect = new DBConnect();
        dbConnect.dbConnection();

        ClientModel clientModel = new ClientModel(dbConnect);
        clientModel.deletePret(dbConnect, numPret);
    }//GEN-LAST:event_jButton9ActionPerformed

    //Bouton mofifier Prêt
    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        int selectedRow = jTablePret.getSelectedRow(); // Obtenez la ligne sélectionnée
        String numPret = (String) jTablePret.getValueAt(selectedRow, 0); // Récupérez le numPret depuis la première colonne
        double solde = Double.parseDouble(jTextFieldMontantPret.getText());

        DBConnect dbConnect = new DBConnect();
        dbConnect.dbConnection();

        ClientModel clientModel = new ClientModel(dbConnect);
        clientModel.updateMontantPret(dbConnect, numPret, solde);

    }//GEN-LAST:event_jButton11ActionPerformed

    //bouton pdf de virement
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int selectedRow = jTableVirement.getSelectedRow(); // Obtenez la ligne sélectionnée

        // Vérifiez si une ligne est sélectionnée
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner une ligne dans le tableau.", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Récupérer les données depuis le tableau sélectionné
        String numCompte = (String) jTableVirement.getValueAt(selectedRow, 0);
        String nomEnvoyeur = (String) jTableVirement.getValueAt(selectedRow, 1);
        String prenomsEnvoyeur = (String) jTableVirement.getValueAt(selectedRow, 2);
        String numCompteB = (String) jTableVirement.getValueAt(selectedRow, 3);
        String nomBeneficiaire = (String) jTableVirement.getValueAt(selectedRow, 4);
        String prenomsBeneficiaire = (String) jTableVirement.getValueAt(selectedRow, 5);
        String montantStr = (String) jTableVirement.getValueAt(selectedRow, 6);
        String dateTransfertStr = (String) jTableVirement.getValueAt(selectedRow, 7);

        // Convertir montant en Double
        Double montant = Double.parseDouble(montantStr);

        // Convertir la chaîne de caractères de date en objet java.util.Date
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS");
        Date utilDateTransfert = null;
        try {
            utilDateTransfert = (Date) sdf.parse(dateTransfertStr);
        } catch (java.text.ParseException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Convertir java.util.Date en java.sql.Timestamp
        Timestamp sqlDateTransfert = new Timestamp(utilDateTransfert.getTime());

        DBConnect dbConnect = new DBConnect();
        dbConnect.dbConnection();

        ClientModel clientModel = new ClientModel(dbConnect);

        // Récupérer le solde de l'envoyeur
        Double soldeEnvoyeur = clientModel.getClientSolde(dbConnect, numCompte);

        // Vérifiez que le solde n'est pas nul
        if (soldeEnvoyeur == null) {
            JOptionPane.showMessageDialog(this, "Erreur de récupération du solde. Veuillez vérifier les données.", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Appeler la méthode pour générer le PDF de virement
        clientModel.genererVirement(sqlDateTransfert, numCompte, "005", nomEnvoyeur, prenomsEnvoyeur, soldeEnvoyeur, numCompteB, nomBeneficiaire, prenomsBeneficiaire, montant);

        // Afficher une boîte de dialogue confirmant que le PDF a été généré
        JOptionPane.showMessageDialog(this, "Le PDF du virement a été généré avec succès.", "Succès", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton8ActionPerformed

    //bouton mail de prêt
    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        int selectedRow = jTablePret.getSelectedRow(); // Obtenez la ligne sélectionnée

        // Vérifiez si une ligne est sélectionnée
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner une ligne dans le tableau.", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Récupérer les données depuis le tableau sélectionné
        String numCompte = (String) jTablePret.getValueAt(selectedRow, 1);
        Object montantPreteObj = jTablePret.getValueAt(selectedRow, 4);
        Object datePretObj = jTablePret.getValueAt(selectedRow, 5);

        double montant_Prete = 0.0;
        try {
            // Convertir l'objet en String
            String montantPreteStr = (montantPreteObj != null) ? montantPreteObj.toString() : "";

            // Convertir la String en Double
            montant_Prete = Double.parseDouble(montantPreteStr);

            // Vérifier si le montant est valide (non négatif)
            if (montant_Prete <= 0.0) {
                throw new NumberFormatException("Montant de prêt invalide : " + montantPreteStr);
            }

            DBConnect dbConnect = new DBConnect();
            dbConnect.dbConnection();

            ClientModel clientModel = new ClientModel(dbConnect);

            try {
                // Récupérer les informations du client pour le mail
                String[] clientInfo = clientModel.getClientInfo(dbConnect, numCompte);
                if (clientInfo == null || clientInfo.length < 3) {
                    System.out.println("Informations du client non trouvées pour le compte : " + numCompte);
                    return;
                }

                String nom = clientInfo[0];
                String prenoms = clientInfo[1];
                String mail = clientInfo[2];

                // Convertir la valeur de la date en Timestamp
                Timestamp datePret = null;
                if (datePretObj instanceof Timestamp) {
                    datePret = (Timestamp) datePretObj;
                } else if (datePretObj instanceof String) {
                    try {
                        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                        Date parsedDate = dateFormat.parse((String) datePretObj);
                        datePret = new Timestamp(parsedDate.getTime());
                    } catch (java.text.ParseException ex) {
                        Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    System.out.println("Type de date non pris en charge : " + datePretObj.getClass().getName());
                    JOptionPane.showMessageDialog(this, "Type de date non pris en charge : " + datePretObj.getClass().getName(), "Erreur", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                // Calculer la date limite de remboursement (200 jours après le prêt)
                Calendar cal = Calendar.getInstance();
                cal.setTime(datePret);
                cal.add(Calendar.DAY_OF_YEAR, 200);
                String dueDate = new SimpleDateFormat("yyyy-MM-dd").format(cal.getTime());

                // Formatter le montant à rembourser
                DecimalFormat df = new DecimalFormat("#.##");
                String montantRembourse = df.format(montant_Prete * 1.10);

                // Envoyer la notification par e-mail
                Mail mailer = new Mail();
                mailer.sendNotification(mail, nom + " " + prenoms, montantRembourse, dueDate);

                // Afficher une boîte de dialogue confirmant l'envoi du mail
                JOptionPane.showMessageDialog(this, "E-mail envoyé avec succès.", "Succès", JOptionPane.INFORMATION_MESSAGE);

            } catch (SQLException | MessagingException | UnsupportedEncodingException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Erreur lors de l'envoi du mail : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Montant de prêt invalide : " + montantPreteObj, "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    //Bouton annuler de virement
    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        HomePage.jComboBoxNumCompteEnvoyeur.setEnabled(true);
        HomePage.jTextFieldMontantVirement.setText("");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jTablePretMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePretMouseReleased

    }//GEN-LAST:event_jTablePretMouseReleased

    //Bouton annuler dans pret
    private void jButtonAnnulerpretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerpretActionPerformed
        HomePage.jComboBoxNumComptePret.setEnabled(true);
        HomePage.jTextFieldMontantPret.setText("");
        HomePage.jTextFieldnumPret.setText("");
    }//GEN-LAST:event_jButtonAnnulerpretActionPerformed

    //bouton modifier virement
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        String oldNumCompteBeneficiaire = (String) jComboBoxNumCompteBeneficiaire.getSelectedItem();
        double newMontant = Double.parseDouble(jTextFieldMontantVirement.getText());
        String newNumCompteBeneficiaire = oldNumCompteBeneficiaire; // Initialise avec l'ancien numéro de compte bénéficiaire par défaut

        // Vérifier si le numéro de compte bénéficiaire a été modifié dans l'interface utilisateur
        if (jComboBoxNumCompteBeneficiaire.isEditable()) {
            newNumCompteBeneficiaire = (String) jComboBoxNumCompteBeneficiaire.getSelectedItem();
        }

        DBConnect dbConnect = new DBConnect();
        dbConnect.dbConnection();

        ClientModel clientModel = new ClientModel(dbConnect);

        // Appel de la méthode pour mettre à jour le virement
        clientModel.updateVirement(dbConnect, newNumCompteBeneficiaire, newMontant);
    }//GEN-LAST:event_jButton4ActionPerformed

    //recherche de client
    private void jTextFieldRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRechercheActionPerformed

    }//GEN-LAST:event_jTextFieldRechercheActionPerformed

    //Ajout de listener dans le champ de recherche
    private void initializeSearchField() {
        jTextFieldRecherche.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                performSearch();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                performSearch();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                performSearch();
            }
        });
    }

    private void performSearch() {
        String searchTerm = jTextFieldRecherche.getText().trim();
        searchClient(searchTerm);
    }

    private void searchClient(String searchTerm) {
        ResultSet rs;
        String[] columns = {"numCompte", "Nom", "Prenoms", "Tel", "Mail", "Solde"};
        DefaultTableModel model = new DefaultTableModel(null, columns);

        String query = "SELECT numCompte, Nom, Prenoms, Tel, Mail, Solde FROM client WHERE numCompte LIKE ? OR Nom LIKE ? OR Prenoms LIKE ?";

        DBConnect dbConnect = new DBConnect();
        dbConnect.dbConnection();

        try (PreparedStatement pstmt = dbConnect.connection.prepareStatement(query)) {
            pstmt.setString(1, "%" + searchTerm + "%");
            pstmt.setString(2, "%" + searchTerm + "%");
            pstmt.setString(3, "%" + searchTerm + "%");
            rs = pstmt.executeQuery();

            while (rs.next()) {
                String[] row = new String[6];
                row[0] = rs.getString("numCompte");
                row[1] = rs.getString("Nom");
                row[2] = rs.getString("Prenoms");
                row[3] = rs.getString("Tel");
                row[4] = rs.getString("Mail");
                row[5] = String.valueOf(rs.getDouble("Solde"));
                model.addRow(row);
            }

            jTableCli.setModel(model);
        } catch (SQLException ex) {
            System.out.println("Erreur lors de la recherche du client: " + ex);
        }
    }

    //bouton suprimer dans rendre
    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        String numrendu = (String) jTextFieldNumRendu.getText();

        DBConnect dbConnect = new DBConnect();
        dbConnect.dbConnection();

        ClientModel clientModel = new ClientModel(dbConnect);
        clientModel.supprimerRendre(dbConnect, numrendu);
    }//GEN-LAST:event_jButton16ActionPerformed

    //Bouton ajout dans remboursement
    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        String numpret = (String) jTextFieldnumpretrendre.getText();
        double rembourse = Double.parseDouble(jTextFieldmontantremboursé.getText()); // Corrected to parse as double

        DBConnect dbConnect = new DBConnect();
        dbConnect.dbConnection();

        ClientModel clientModel = new ClientModel(dbConnect);
        clientModel.addRendre(dbConnect, numpret, rembourse);

        HomePage.jTextFieldnumpretrendre.setText("");
        HomePage.jTextFieldmontantremboursé.setText("");
    }//GEN-LAST:event_jButton15ActionPerformed

    //bouton modifier de rendre
    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        String numpret = (String) jTextFieldnumpretrendre.getText();
        double rembourse = Double.parseDouble(jTextFieldmontantremboursé.getText()); // Corrected to parse as double
        String numrendu = (String) jTextFieldNumRendu.getText();

        DBConnect dbConnect = new DBConnect();
        dbConnect.dbConnection();

        ClientModel clientModel = new ClientModel(dbConnect);
        clientModel.modifierRendre(dbConnect, numrendu, numpret, rembourse);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jTextFieldRestePayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRestePayerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRestePayerActionPerformed

    private void jTextFieldDateRenduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDateRenduActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDateRenduActionPerformed

    private void jTableRendreMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRendreMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableRendreMouseReleased

    //bouton annuler dans rendre
    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        HomePage.jTextFieldNumRendu.setText("");
        HomePage.jTextFieldnumpretrendre.setText("");
        HomePage.jTextFieldRestePayer.setText("");
        HomePage.jTextFieldsituation.setText("");
        HomePage.jTextFieldDateRendu.setText("");
    }//GEN-LAST:event_jButton18ActionPerformed

    //liste déroulante d'affichage
    private void jComboBoxaffichagerembourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxaffichagerembourseActionPerformed
        String selectedSituation = (String) jComboBoxaffichagerembourse.getSelectedItem();

        DBConnect dbConnect = new DBConnect();
        dbConnect.dbConnection();

        ClientModel clientModel = new ClientModel(dbConnect);
        clientModel.tableRendre(selectedSituation);

    }//GEN-LAST:event_jComboBoxaffichagerembourseActionPerformed

    private void jTextFieldMontantVirementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMontantVirementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMontantVirementActionPerformed

    private void initializeComboBox() {
        jComboBoxaffichagerembourse.addItem("Toute situation");
        jComboBoxaffichagerembourse.addItem("Payé d'une part");
        jComboBoxaffichagerembourse.addItem("Tout payé");

        jComboBoxaffichagerembourse.setSelectedIndex(0); // Sélectionner "Toute situation" par défaut
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new HomePage().setVisible(true);

                /* ClientModel cli = new ClientModel();
                cli.table();*/
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonAnnulerpret;
    public static javax.swing.JComboBox<String> jComboBoxNumCompteBeneficiaire;
    public static javax.swing.JComboBox<String> jComboBoxNumCompteEnvoyeur;
    public static javax.swing.JComboBox<String> jComboBoxNumComptePret;
    public static javax.swing.JComboBox<String> jComboBoxaffichagerembourse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JTable jTableCli;
    public static javax.swing.JTable jTablePret;
    public static javax.swing.JTable jTableRendre;
    public static javax.swing.JTable jTableVirement;
    public static javax.swing.JTextField jTextFieldDateRendu;
    public static javax.swing.JTextField jTextFieldMail;
    public static javax.swing.JTextField jTextFieldMontant;
    public static javax.swing.JTextField jTextFieldMontantPret;
    public static javax.swing.JTextField jTextFieldMontantVirement;
    public static javax.swing.JTextField jTextFieldNom;
    public static javax.swing.JTextField jTextFieldNumCompte;
    public static javax.swing.JTextField jTextFieldNumRendu;
    public static javax.swing.JTextField jTextFieldPrenoms;
    private javax.swing.JTextField jTextFieldRecherche;
    public static javax.swing.JTextField jTextFieldRestePayer;
    private javax.swing.JTextField jTextFieldSituation;
    public static javax.swing.JTextField jTextFieldTel;
    public static javax.swing.JTextField jTextFieldmontantremboursé;
    public static javax.swing.JTextField jTextFieldnumPret;
    public static javax.swing.JTextField jTextFieldnumpretrendre;
    public static javax.swing.JTextField jTextFieldsituation;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
